### ISSUE TITLE
Source site pgl.yoyo.org redirects to https

### ISSUE THREAD

**Issue by msadek** [suntong/dbab--pre1.3.3#10]
after running `dbab-get-list ` the file **dbab.adblock.conf**  contains HTML redirect output

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://pgl.yoyo.org/">here</a>.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at pgl.yoyo.org Port 80</address>
</body></html>
```
So I suggest editing the url to make it

`https://pgl.yoyo.org/adservers/serverlist.php?hostformat=dnsmasq&showintro=0&mimetype=plaintext`

**Comment by suntong** [comment]
Thanks a lot, will do...
