### ISSUE TITLE
Is it simpler to block by redirecting requests to 0.0.0.0 instead of using pixelserv?

### ISSUE THREAD

**Issue by ghost** [suntong/dbab--pre1.3.3#3]
Wouldn't blocking be simpler, more efficient, faster, and use less processing power by redirecting requests to 0.0.0.0 instead of using pixelserv?

**Comment by suntong** [comment]
Hmm..., do you mean conceptually, or practically? 

Conceptually, yes, blocking might be more efficient, but practically, how to block? I.e., from an HTML page, there might be 10 ads, from different source, and of different types, how to block each one of them and still show the page properly? 

Also, I'm not sure but the "` 0.0.0.0`" is a listening address, i.e., you can't send request to it and expect answers from it:

![image](https://user-images.githubusercontent.com/422244/32004826-b1ce790c-b970-11e7-9e7f-4e1ac43ac6f4.png)

**Comment by ghost** [comment]
I mean practically. Why not just redirect every request to 0.0.0.0 as would
happen with a hosts file? Surely this would just block the ads without
needing pixelserv.
What is the problem with this approach?

**Comment by suntong** [comment]
Did you just replied the email or you've seen my updated answer 

> the "0.0.0.0" is a listening address...

**Comment by ghost** [comment]
OK. I've read some more and I think I get it.
