### ISSUE TITLE
Not a pixel, but a browser error. why?

### ISSUE THREAD

**Issue by wilbert-vb** [suntong/dbab--pre1.3.3#5]
![screenshot_20180414_131751](https://user-images.githubusercontent.com/5875366/38771314-b171bb02-3fe6-11e8-8101-cd0b72e69086.png)

This screen capture shows a browser error, while dnsmasq on my Raspberry Pi is responding to the request. Why would I not 'see' a pixel?

http://192.168.1.1/ returns a page with a pixel

Thank you very much.

**Comment by suntong** [comment]
> http://192.168.1.1/ returns a page with a pixel

From which machine/browser? 

> This screen capture shows a browser error

From which machine?

> Raspberry Pi is responding to the request

What does it get?

Have you tried anything else?

**Comment by wilbert-vb** [comment]
From a linux desktop (192.168.1.155/24) with Firefox 59.0.2

DNSmasq log:

```
Apr 15 10:31:37 dnsmasq[2391]: query[A] pubads.g.doubleclick.net from 192.168.1.155
Apr 15 10:31:37 dnsmasq[2391]: config pubads.g.doubleclick.net is 192.168.1.1
Apr 15 10:31:37 dnsmasq[2391]: query[AAAA] pubads.g.doubleclick.net from 192.168.1.155
Apr 15 10:31:37 dnsmasq[2391]: config pubads.g.doubleclick.net is NODATA-IPv6
```

What else should I try?

**Comment by suntong** [comment]
What's your output of `grep doubleclick /etc/dnsmasq.d/dbab.adblock.conf`?

Mine is:

```
$ grep doubleclick /etc/dnsmasq.d/dbab.adblock.conf
address=/doubleclick.com/192.168.2.101
address=/doubleclick.de/192.168.2.101
address=/doubleclick.net/192.168.2.101
```

What's the IP of yours, `192.168.1.1`?

That `NODATA-IPv6` from your log, I have no idea. You may need to figure out yourself. 

Also, what's the answer to my first three questions? I mean, I'm still not clear what you are having from what. Unless I have a clear picture, the troubleshooting would be very hard, because there might be tons of possibilities.

**Comment by wilbert-vb** [comment]
```
root@rpi2-server:~# grep doubleclick /etc/dnsmasq.d/dbab.adblock.conf
address=/doubleclick.com/192.168.1.1
address=/doubleclick.de/192.168.1.1
address=/doubleclick.net/192.168.1.1
root@rpi2-server:~#
```
I get the same error message on two desktop systems, Firefox 59 on Debian and Fedora linux and also in Edge browser on Windows 10. Dnsmasq on my pi2 serves the ip addresses and dns settings.

Perhaps the clue is here: 
https://github.com/pi-hole/pi-hole/issues/140

**Comment by suntong** [comment]
Might be. But regardless whether it is or not, It'll be a Raspberry Pi specific problem, which I have no experience at all. So closing it here, and please ask instead in a Raspberry Pi specific support forum. Ask for how to check and config its firewall as well while you were there. Best luck.

**Comment by wilbert-vb** [comment]
I generated dbab.adblock-ipv6.conf with ipv6 addresses:
```
sed 's/192.168.1.1/2602:306:cdb5:67d0:ba27:ebff:fe0a:c6f5/g' dbab.adblock.conf > dbab.adblock-ipv6.conf
```
Before:
```
Apr 15 15:06:21 dnsmasq[3288]: query[A] googleads.g.doubleclick.net from 192.168.1.156
Apr 15 15:06:21 dnsmasq[3288]: config googleads.g.doubleclick.net is 192.168.1.1
Apr 15 15:06:21 dnsmasq[3288]: query[AAAA] googleads.g.doubleclick.net from 192.168.1.156
Apr 15 15:06:21 dnsmasq[3288]: config googleads.g.doubleclick.net is NODATA-IPv6
```
After:
```
Apr 15 15:01:44 dnsmasq[3073]: query[A] pubads.g.doubleclick.net from 192.168.1.156
Apr 15 15:01:44 dnsmasq[3073]: config pubads.g.doubleclick.net is 192.168.1.1
Apr 15 15:01:44 dnsmasq[3073]: query[AAAA] pubads.g.doubleclick.net from 192.168.1.156
Apr 15 15:01:44 dnsmasq[3073]: config pubads.g.doubleclick.net is 2602:306:cdb5:67d0:ba27:ebff:fe0a:c6f5
```
